### ISSUE TITLE
provide short installation guide

### ISSUE THREAD

**Issue by bnussbau** [dpfaffenbauer/pimcore-docker-compose#11]
HI,
Thanks for creating this repo. It would be easier to get started if a small installation guide was provided.
Took me some time to figure out that you need to run `pimcore-install --mysql-host-socket=db` and the set the php memory_limit >= 1024MB to be able to run the installer.
Cheers

**Comment by dpfaffenbauer** [comment]
I am happy to accept a PR for that.
