### ISSUE TITLE
Getting classes failed error for new pimcore installation

### ISSUE THREAD

**Issue by chaitanyadatkhile** [dpfaffenbauer/pimcore-docker-compose#15]
Hello,

Getting classes failed error for new pimcore() installation.

The error is as below.

[Note] Installing classes failed. Please run the following command manually.

/usr/local/bin/php /var/www/html/bin/console pimcore:deployment:classes-rebuild -c
![pimcore-error](https://user-images.githubusercontent.com/33537385/57678495-f3b4a000-7646-11e9-9719-7c5614e7f027.jpg)

Also getting the below error.

Skipping migrations ... (either Pimcore is not installed yet or current status of migrations is not available)

**Comment by dpfaffenbauer** [comment]
That’s a Pimcore issue that’s already been fixed. There has been no new version released yet.
