### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mdocter** [dpfaffenbauer/pimcore-docker-compose#16]
Hi Dominik,

Thank you for all the great pimcore content and CoreShop!
I tried this docker-compose setup yesterday evening and followed the installation guide and got it to work, but the performance is really bad. Installation of the e-commerce demo took about an hour and running it is also not production comparable. I already assigned 8GB RAM and 6 CPU cores to my Docker (on Windows) installation, but still no luck. This seems strange to me. Am I doing something wrong? Do I need to assign more hardware resources? Do you have any tips?
Greatly appreciated!

Kind regards,

Maarten

**Comment by dpfaffenbauer** [comment]
welcome to docker on windows or mac with symfony ;)

Nothing you can do, docker is just very, very, very slow on Mac or Windows.

**Comment by mdocter** [comment]
Thanks Dominik. Not the answer I was hoping for, but sure loud and clear 👍 
Let's wait until Windows Subsystem for Linux 2 is released.
