### ISSUE TITLE
Hanging on compose up pimcore-debug-php

### ISSUE THREAD

**Issue by kraigmustard** [dpfaffenbauer/pimcore-docker-compose#17]
Hi there,

Just testing this for the first time but it seems to be hanging on the pimcore-debug-php when composing up. Followed instruction down to the letter but not sure what is wrong or how to fix. Could I get some help please?
![image](https://user-images.githubusercontent.com/17261469/60231049-569e8580-98db-11e9-88fc-754db74978b9.png)

**Comment by dpfaffenbauer** [comment]
that is odd... not sure why it happens. can you try removing the php image from the docker-compose file and try again?

Could also be cause you are on windows, and I never tested these images on windows.

**Comment by kraigmustard** [comment]
Ah cheers for the reply mate. Managed to get it going. Apparently as soon as you install docker on windows you need to grant it permission for the drive or folder you want to allow to be writable. That's why php was hanging as it was waiting for permission. All good now.

**Comment by dpfaffenbauer** [comment]
cool, glad it works now.

have a nice day down under mate ;)
