### ISSUE TITLE
error during execution of ./vendor/bin/pimcore-install

### ISSUE THREAD

**Issue by choppe3766** [dpfaffenbauer/pimcore-docker-compose#18]
Hi, first of all thank for your great work :)

If I try to install pimcore i get the following error:

`* Warning: Declaration of Pimcore\Bundle\CoreBundle\EventListener\LegacyTemplateListener::onKernelView(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent $event) should be compatible with Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelView(Symfony\Component\HttpKernel\Event\KernelEvent $event)`

and the install script stops on 50%.

Could this be an issue with the latest pimcore 6 version, because pimcore has changed the symfony version from 3 to 4.

Thanks
Chris

**Comment by dpfaffenbauer** [comment]
thats a pimcore issue

**Comment by baloraki** [comment]
> Hi, first of all thank for your great work :)
> 
> If I try to install pimcore i get the following error:
> 
> `* Warning: Declaration of Pimcore\Bundle\CoreBundle\EventListener\LegacyTemplateListener::onKernelView(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent $event) should be compatible with Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelView(Symfony\Component\HttpKernel\Event\KernelEvent $event)`
> 
> and the install script stops on 50%.
> 
> Could this be an issue with the latest pimcore 6 version, because pimcore has changed the symfony version from 3 to 4.
> 
> Thanks
> Chris

Hi, have you solve the problem?

**Comment by dpfaffenbauer** [comment]
Please ask that on the pimcore GitHub, this is Not a Support project for pimcore
