### ISSUE TITLE
Problem with DB Container

### ISSUE THREAD

**Issue by DudeFN** [dpfaffenbauer/pimcore-docker-compose#22]
Hey 
I followed the instructions from the readme. Unfortunately during the start of the container I get the following message:

```
pimcore-mariadb | 2019-11-23 23:03:35 140708036442112 [ERROR] Plugin 'InnoDB' init function returned error.
pimcore-mariadb | 2019-11-23 23:03:35 140708036442112 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
pimcore-mariadb | 2019-11-23 23:03:35 140708036442112 [Note] Plugin 'FEEDBACK' is disabled.
pimcore-mariadb | 2019-11-23 23:03:35 140708036442112 [ERROR] Unknown/unsupported storage engine: InnoDB
pimcore-mariadb | 2019-11-23 23:03:35 140708036442112 [ERROR] Aborting
```

I tried to use a more recent version (mariadb:10.3.13) - the container runs without any errors. Yeay...

But when I try to connect to the db container, I cannot establish a connection either default 'pimcore' user nor as 'root' user, I am unable to connect to the database during install process 
```
Starting the install process...

  0/11 [>---------------------------]   0%
                                                                                                                
 [ERROR] The following errors were encountered during installation                                                      
                                                                                                                        
 * Couldn't establish connection to MySQL: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
```

Even inside the db container I get the following message

```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

Do I miss something? Or am I doing something wrong? Do you have any clue how I could fix that?

**Comment by dpfaffenbauer** [comment]
I got no idea, sorry

**Comment by Anne-chaG** [comment]
Hey ! 

I'm facing same issue ! 
I tried to install PIMCORE with docker on Windows 10 Pro (using Docker Desktop).
Everything run fine until I use `composer install` command on my php container. 
I've got that error message 
`Host '172.18.0.3' is not allowed to connect to this mariaDB server`

@DudeFN Did you find a solution ?
