### ISSUE TITLE
Database installation is stalling at 54% after pimcore install command. 

### ISSUE THREAD

**Issue by praasanthdasika** [dpfaffenbauer/pimcore-docker-compose#28]
I waited all night for db installation to complete and it never completed db installation stalled at 54%. I exited the process and accessed the website, website is running but i am not able to get login into the website using my admin username and password

**Comment by dpfaffenbauer** [comment]
sorry, not a problem with these images

**Comment by xanthos84** [comment]
it is, because i also get until 54%...

" Aborted connection 8 to db: 'pimcore' user: 'pimcore' host: '192.168.32.5' (Got an error reading communication packets) "
