### ISSUE TITLE
Would this compose work on Windows?

### ISSUE THREAD

**Issue by kyl3david** [dpfaffenbauer/pimcore-docker-compose#29]
root@fbc9835c7b75:/var/www/html#
root@fbc9835c7b75:/var/www/html# #increase the memory_limit to >= 512MB as required by pimcore-install
root@fbc9835c7b75:/var/www/html# echo 'memory_limit = 512M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini;
 apache2root@fbc9835c7b75:/var/www/html# service apache2 reload

#run installer
./vendor/bin/pimcore-install --mysql-host-socket=db --mysql-username=pimcore-skeleton --mysql-password=pimcore-[....] Re[ ok ng Apache httpd web server: apache2skeleton --mysql-database=pimcore-skeleton .
root@fbc9835c7b75:/var/www/html#
root@fbc9835c7b75:/var/www/html# #run installer
root@fbc9835c7b75:/var/www/html# ./vendor/bin/pimcore-install --mysql-host-socket=db --mysql-username=pimcore-skeleton --mysql-password=pimcore-skeleton --mysql-database=pimcore-skeleton

[WARNING] Using sensitive options (--mysql-username) on the command line interface can be insecure.
Consider using the interactive prompt or the PIMCORE_INSTALL_MYSQL_USERNAME environment variable instead.

[WARNING] Using sensitive options (--mysql-password) on the command line interface can be insecure.
Consider using the interactive prompt or the PIMCORE_INSTALL_MYSQL_PASSWORD environment variable instead.

 Admin username:
 >

 [ERROR] admin-username cannot be empty

 Admin username:
 > admin

 Admin password (input will be hidden):
 >

 This will install Pimcore with the given settings. Do you want to continue? (yes/no) [yes]:
 >

Running installation. You can find a detailed install log in var/installer/logs/prod.log

Booting new kernel...

  5/11 [============>---------------]  45%

 [ERROR] The following errors were encountered during installation

 * Failed to remove directory "/var/www/html/var/cach~/prod/Container9hrAqJS": rmdir(/var/www/html/var/cach~/prod/Container9hrAqJS): Directory not empty

**Comment by dpfaffenbauer** [comment]
sorry, no idea, not officially supported here.

**Comment by kyl3david** [comment]
Cool, no problem.
Thanks for the reply 👍
