### ISSUE TITLE
Source code is installed in home directory of user?

### ISSUE THREAD

**Issue by andreas-gruenwald** [dpfaffenbauer/pimcore-docker-compose#30]
When installing Pimcore inside the docker container, I realised that the source code will be installed in the home-directory of the user outside the docker container.

Example:
```shell
cd /home/docker; # home directory of current user
docker exec -it pimcore-php bash # enter container
# install pimcore inside docker
exit # exit container
cd # go to home directory of user
ls  # user directory contains src/, app/, bin/, etc.
```

Why is that? Is it because the php-container is mounted with volume ``- .:/var/www/html:cached``? What is the meaning of the dot?

On the one hand I am curious. On the other hand I want to host a container where it is possible to edit the code directly inside the container. I am wondering, whether provisioning the code inside the user's home directory is already the best way to do it, or if it would be better to add the classes directly inside the container, and make them accessible via a docker ssh port.

**Comment by dpfaffenbauer** [comment]
Yes, cause the folder is mounted. `.` is the current working directory.

Sorry, but I can not help you with basic docker questions/needs here
