### ISSUE TITLE
Connecting PHPStorm with XDEBUG

### ISSUE THREAD

**Issue by andreas-gruenwald** [dpfaffenbauer/pimcore-docker-compose#31]
In the docker image ``dpfaffenbauer/pimcore:PHP7.2-apache-debug`` xdebug is already installed and setup. 
However, I cannot connect PHPStorm to it.

As far as I know, PHPStorm is listening on port 9000 for debug connections.

So I added an additional port mapping for the ``php-debug`` section in your ``docker-compose.yml`` and restarted the services.
Essentially I just map port 9000 of the container to the port 9000 of the host.

Still PHPStorm is not detecting a connection.

Is this the wrong approach?
Can you give advice on how you managed to establish a connection or add a small section about it to the readme?

**Comment by dpfaffenbauer** [comment]
Windows or Mac?

On Mac it works with that setup without even exposing the Port, here is my PHP Storm Config:

<img width="581" alt="Bildschirmfoto 2020-07-13 um 08 04 12" src="https://user-images.githubusercontent.com/5981845/87275905-73562d00-c4df-11ea-9bec-ed7f88b4ceda.png">

**Comment by andreas-gruenwald** [comment]
On Windows.
My settings are similar to yours, but I am working with a remote server.
![image](https://user-images.githubusercontent.com/16687355/87283100-3e54d500-c4f5-11ea-8f89-86d67217615b.png)

Probably need to dig deeper...

**Comment by dpfaffenbauer** [comment]
well, connecting to a remote host is a completely different story...

**Comment by andreas-gruenwald** [comment]
Connecting with a remote host works for all my other Pimcore projects. I will post the solution here as soon as I found out.

**Comment by dpfaffenbauer** [comment]
this images are designed to be used for local dev, not remote development. I don't see the point of a remote docker container for development.

**Comment by andreas-gruenwald** [comment]
> this images are designed to be used for local dev, not remote development. I don't see the point of a remote docker container for development.

Let's call it "environmental constraints".  ;-)

I made it run. The solution was to edit
```
/usr/local/etc/php/conf.d/20-xdebug.ini
```

and activate remote connect back feature.
```
xdebug.remote_connect_back = 1
```

Would be great if the image could be shipped with this setting as a default.

**Comment by dpfaffenbauer** [comment]
the images are maintained under pimcore/docker now, you could create a PR there
