### ISSUE TITLE
Got an error from origin docker-compose up command: Forbidden You don't have permission to access / on this server.

### ISSUE THREAD

**Issue by supaket** [dpfaffenbauer/pimcore-docker-compose#5]
Hi

After try to docker-compose up I got this message

Forbidden
You don't have permission to access / on this server.
Apache/2.4.10 (Debian) Server at localhost Port 2000

I run on docker via Mac

**Comment by dpfaffenbauer** [comment]
try running ```chown -R www-data: .``` inside the docker php container. Seems like permissions are messed up, what usually happens on docker for osx.

**Comment by supaket** [comment]
Thanks @dpfaffenbauer, it's work now.

**Comment by simiii** [comment]
Have the same issue with my docker toolbox vm on windows. Inside which folder do I need to execute the `chow -R www-data: .` command?

**Comment by dpfaffenbauer** [comment]
what image and how does your docker-compose look like?

**Comment by virtualweb-at** [comment]
I missed that i have to mount the Volume to the Host where the Pimcore Code is. Now it is working.

Then it was not clear to me that i have to define the Database Host as "db", maybe this 2 things could be added to the Short Description for others.

**Comment by dpfaffenbauer** [comment]
Well, volume: sure, thats how it works.

I use PHP7.2 and I work with the latest version of Pimcore and it works fine.

DB-Host: Well, you need of course know how docker-compose works and how networking is done. That is fundamental to work with docker -> but, you could create a PR for that if you want :)
