### ISSUE TITLE
Purpose of project and how to setup pimcore development with docker

### ISSUE THREAD

**Issue by simiii** [dpfaffenbauer/pimcore-docker-compose#6]
It would be nice to have more information on how to use the project in a pimcore development project.

Is there anything suitable?

Thanks in advance

**Comment by dpfaffenbauer** [comment]
Well, nothing special here. You need to know how to use docker and pimcore, and thats basically it.

What I do, is to put the docker-compose.yml inside my pimcore root dev folder and run ```docker-compose up``` thats about it.

**Comment by simiii** [comment]
Thank you very much for your help.
